FROM maven:3.9.6-amazoncorretto-21 as build
RUN mkdir -p /product_api
WORKDIR /product_api
COPY pom.xml /product_api
COPY src /product_api/src
RUN mvn -f /product_api/pom.xml clean package

FROM amazoncorretto:21.0.2-alpine3.19
COPY --from=build /product_api/target/* app.jar
EXPOSE 8080/tcp
ENTRYPOINT ["java", "-Dspring.profiles.active=docker", "-jar", "app.jar"]
