spring:
    application.name: monsters
    data:
        mongodb:
            host: mongo-database
            port: 27017
            username: user
            password: password
            authentication-database: admin
            database: monsters-database
            uuid-representation: standard
