# This compose is to test between authentication-api and mongo only
version: '3.3'
services:
    mongo-database:
        ports: ['27017:27017']
        container_name: mongo-database
        restart: on-failure
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        image: mongo
    test-authentication-api:
        build: 
            context: .
            dockerfile: test.dockerfile
        container_name: test-authentication-api
        depends_on: ['mongo-database']
